---
- name: install and configure ntp service
  hosts: dev
  become: yes
  tasks:

    - name: install ntp
      yum:
       name: ntp
       status: present
      tags: install_ntp,start_ntp

    - name: deply ntp.conf file to client
      template:
       src=templates/ntp.j2
       dest=/etc/ntp.conf
      notify: start_ntp_client
      tags: copy_ntp_conf,start_ntp

  handlers:

    - name: start_ntp_client
      service:
       name=ntpd
       state=restarted
       enabled=yes




