---
- name: install webserver
  hosts: web
  become: yes
  tasks:
    - name: install httpd package
      yum: 
        name: httpd
        state: latest

    - name: Ansible create file with content in it
      template:
        dest: /var/www/html/index.html
        content: |
          html 
          image url= "{{image_url}}"
          
    - name: start and enable httpd service on system reboot
      service:
        name: httpd
        state: started
        enabled: yes
        notify: restart httpd
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
        